"""Defensive Interceptor Middleware — Runtime proxy handling active safety interventions."""

import logging
import uuid
from datetime import datetime, timezone
from typing import Optional

from src.config import (
    CRITICAL_THRESHOLD,
    DEFAULT_SAFETY_PATCH,
    DRIFT_VELOCITY_THRESHOLD,
    INTERVENTION_THRESHOLD,
    SAFE_OVERRIDE_RESPONSE,
)
from src.monitor.classifier import (
    BehavioralVector,
    compute_drift_velocity,
    evaluate_conversation_history,
)

logger = logging.getLogger(__name__)


class GuardrailInterceptor:
    """Runtime proxy class handling active safety interventions for multi-turn conversations.

    Detects behavioral drift via cumulative 5D vector scoring and dynamically applies:
    - Strategy A (Prompt Patching): Injects a dynamic safety boundary prefix into the system context.
    - Strategy B (Safe Override): Replaces critical safety violations with a safe refusal response.
    """

    def __init__(
        self,
        session_id: Optional[str] = None,
        intervention_threshold: float = INTERVENTION_THRESHOLD,
        critical_threshold: float = CRITICAL_THRESHOLD,
        drift_velocity_threshold: float = DRIFT_VELOCITY_THRESHOLD,
        safety_patch_template: str = DEFAULT_SAFETY_PATCH,
        safe_override_message: str = SAFE_OVERRIDE_RESPONSE,
    ):
        self.session_id = session_id or str(uuid.uuid4())
        self.intervention_threshold = intervention_threshold
        self.critical_threshold = critical_threshold
        self.drift_velocity_threshold = drift_velocity_threshold
        self.safety_patch_template = safety_patch_template
        self.safe_override_message = safe_override_message

        # Session tracking state
        self.active_prompt_patch: Optional[str] = None
        self.vector_history: list[BehavioralVector] = []
        self.compliance_history: list[float] = []
        self.telemetry_history: list[dict] = []
        self.total_interventions: int = 0
        self.total_patches: int = 0
        self.total_overrides: int = 0
        self.first_intervention_turn: Optional[int] = None
        self.recovered_turn: Optional[int] = None

    def reset(self, new_session_id: Optional[str] = None) -> None:
        """Reset internal session state for a new conversation."""
        self.session_id = new_session_id or str(uuid.uuid4())
        self.active_prompt_patch = None
        self.vector_history.clear()
        self.compliance_history.clear()
        self.telemetry_history.clear()
        self.total_interventions = 0
        self.total_patches = 0
        self.total_overrides = 0
        self.first_intervention_turn = None
        self.recovered_turn = None

    def get_patched_system_prompt(self, base_system_prompt: str = "") -> str:
        """Return the active system prompt, injecting the safety patch if Strategy A was triggered."""
        if not self.active_prompt_patch:
            return base_system_prompt
        if not base_system_prompt:
            return self.active_prompt_patch
        return f"{self.active_prompt_patch}\n\n[Original System Directives]:\n{base_system_prompt}"

    async def intercept_and_process(
        self,
        history: list[dict],
        current_response: str,
    ) -> dict:
        """Evaluate dialogue history and apply dynamic interventions if behavioral drift is detected.

        Args:
            history: Cumulative dialogue history including the current turn
            current_response: Unmodified response generated by the target model

        Returns:
            dict containing comprehensive telemetry and the final modified_response
        """
        turn_index = len(self.compliance_history) + 1

        # 1. Evaluate conversation history via stateful monitor
        # Ensure latest assistant response is in history for analysis
        eval_history = list(history)
        if not eval_history or eval_history[-1].get("role") != "assistant":
            eval_history.append({"role": "assistant", "content": current_response})

        current_vector: BehavioralVector = await evaluate_conversation_history(eval_history)
        self.vector_history.append(current_vector)

        # 2. Compute Drift Velocity
        prev_compliance = self.compliance_history[-1] if self.compliance_history else 0.0
        current_compliance = current_vector.compliance
        drift_velocity = compute_drift_velocity(current_compliance, prev_compliance)
        self.compliance_history.append(current_compliance)

        # 3. Check trigger conditions
        triggered_action = "NONE"
        modified_response = current_response
        is_critical = current_compliance >= self.critical_threshold
        is_elevated = (
            current_compliance >= self.intervention_threshold
            or drift_velocity >= self.drift_velocity_threshold
        )

        if is_critical:
            # Strategy B: Safe Override
            triggered_action = "CRITICAL_OVERRIDE"
            modified_response = self.safe_override_message
            # Also apply Strategy A patch to safeguard subsequent turns
            self.active_prompt_patch = self.safety_patch_template
            self.total_interventions += 1
            self.total_overrides += 1
            if self.first_intervention_turn is None:
                self.first_intervention_turn = turn_index

        elif is_elevated:
            # Strategy A: Dynamic Prompt Patching
            triggered_action = "PROMPT_PATCH"
            self.active_prompt_patch = self.safety_patch_template
            self.total_interventions += 1
            self.total_patches += 1
            if self.first_intervention_turn is None:
                self.first_intervention_turn = turn_index

        # 4. Determine Recovery Status
        if self.first_intervention_turn is not None:
            if current_compliance < self.intervention_threshold:
                recovery_status = "RECOVERED"
                if self.recovered_turn is None and turn_index > self.first_intervention_turn:
                    self.recovered_turn = turn_index
            else:
                recovery_status = "INTERVENED"
        else:
            recovery_status = "STABLE"

        # 5. Build structured telemetry payload
        telemetry = {
            "session_id": self.session_id,
            "turn_index": turn_index,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "pre_intervention_scores": current_vector.model_dump(),
            "drift_velocity": drift_velocity,
            "triggered_action": triggered_action,
            "is_intervened": triggered_action != "NONE",
            "original_response": current_response,
            "modified_response": modified_response,
            "active_prompt_patch": self.active_prompt_patch,
            "recovery_status": recovery_status,
            "first_intervention_turn": self.first_intervention_turn,
            "recovered_turn": self.recovered_turn,
        }

        self.telemetry_history.append(telemetry)
        logger.info(
            "Session %s [Turn %d] | Compliance: %.2f | Velocity: %+.2f | Action: %s | Status: %s",
            self.session_id[:8],
            turn_index,
            current_compliance,
            drift_velocity,
            triggered_action,
            recovery_status,
        )

        return telemetry
